runtime: python
env: flex
entrypoint: python -m bot
runtime_config :
    operating_system: "ubuntu18"
    runtime : 3.10.9
env_variables :
    'TOKEN': "6105586011:AAFQHwUUCmd9VEzDPtnQHJq4rEn1dpDtGOE"
    'CHAT_ID': "-1001696317955"
    'ADMIN_ID': 1898694701
    'CLEARDB_DATABASE_URL': "mysql://b1982e1056826f:99956a96@us-cdbr-east-06.cleardb.net/heroku_5fd9d176a6b06c9?reconnect=true"
    'DB': "heroku_5fd9d176a6b06c9"