runtime: python
env: flex
entrypoint: python -m bot
runtime_config :
    operating_system: "ubuntu18"
    runtime : 3.10.9
env_variables :
    'TOKEN': "6000914104:AAGkm5PxzBbcRCSZLlsM6tt5Kn0yo1Wn4Us"
    'CHAT_ID': "-1001691747162"
    'ADMIN_ID': 1898694701
    'CLEARDB_DATABASE_URL': "mysql://b93e49450c6b8f:a6b1058f@us-cdbr-east-06.cleardb.net/heroku_a2cc31028df0304?reconnect=true"
    'DB': "heroku_a2cc31028df0304"